In [2]:
import numpy as np

def sigmoid(x): #defining the sigmoid function
    return 1 / (1 + np.exp(-x))

def sigmoid_derivative(x):
    return x * (1-x)

training_inputs = np.array([[0, 0, 1], #basic inputs used for training
                            [1, 1, 1],
                            [1, 0, 1],
                            [0, 1, 1]])

training_outputs = np.array([[0, 1, 1, 0]]).T #here T is for transpose

np.random.seed(1)

synaptic_weights = 2 * np.random.random((3, 1)) - 1 #the weights to be used 

print("Random starting synaptic weights: ")
print(synaptic_weights)

for iteration in range(100000): # here the range(number) is the number of iterations to provide for the model
    input_layer = training_inputs
    outputs = sigmoid(np.dot(input_layer, synaptic_weights))

    error = training_outputs - outputs

    adjustments = error * sigmoid_derivative(outputs)

    synaptic_weights += np.dot(input_layer.T, adjustments)

print('Synaptic weights after training: ')
print(synaptic_weights)

print("Outputs after training: ")
print(outputs)

Random starting synaptic weights: 
[[-0.16595599]
 [ 0.44064899]
 [-0.99977125]]
Synaptic weights after training: 
[[12.00870061]
 [-0.2044116 ]
 [-5.8002822 ]]
Outputs after training: 
[[0.00301758]
 [0.99753723]
 [0.99799161]
 [0.00246109]]


- To be noted, here the outputs after training would only be close to our actualy output, and not enitrely correct. This is because the sigmoid function is made to display only closest values, and not exact ones.

In [6]:
import numpy as np

class NeuralNetwork():

    def __init__(self):
        np.random.seed(1)

        self.synaptic_weights = 2 * np.random.random((3, 1)) - 1

    def sigmoid(self, x):
        return 1 / (1 + np.exp(-x))

    def sigmoid_derivative(self, x):
        return x * (1 - x)

    def train(self, training_inputs, training_outputs, training_iterations):

        for iteration in range(training_iterations):

            output = self.think(training_inputs)
            error = training_outputs - output
            adjustments = np.dot(training_inputs.T, error * self.sigmoid_derivative(output))
            self.synaptic_weights += adjustments

    def think(self, inputs):

        inputs = inputs.astype(float)
        output = self.sigmoid(np.dot(inputs, self.synaptic_weights))

        return output


if __name__ == "__main__":

    neural_network = NeuralNetwork()

    print("Random synaptic weights: ")
    print(neural_network.synaptic_weights)

    training_inputs = np.array([[0, 0, 1],
                            [1, 1, 1],
                            [1, 0, 1],
                            [0, 1, 1]])

    training_outputs = np.array([[0, 1, 1, 0]]).T

    neural_network.train(training_inputs, training_outputs, 10000)

    print("Synaptic weights after training: ")
    print(neural_network.synaptic_weights)

    A = str(input('Input 1: '))
    B = str(input('Input 2: '))
    C = str(input('Input 3: '))

    print("New situation -> input data = ", A, B, C)
    print('Output data: ')
    print(neural_network.think(np.array([A, B, C])))

Random synaptic weights: 
[[-0.16595599]
 [ 0.44064899]
 [-0.99977125]]
Synaptic weights after training: 
[[ 9.67299303]
 [-0.2078435 ]
 [-4.62963669]]


Input 1:  1
Input 2:  0
Input 3:  0


New situation -> input data =  1 0 0
Output data: 
[0.99993704]


# Keras Sequential model:

the sequential model is a linear stack of layers.

In [4]:
pip install keras

  Using cached keras-3.6.0-py3-none-any.whl.metadata (5.8 kB)
  Using cached absl_py-2.1.0-py3-none-any.whl.metadata (2.3 kB)
  Using cached rich-13.9.2-py3-none-any.whl.metadata (18 kB)
  Using cached namex-0.0.8-py3-none-any.whl.metadata (246 bytes)
  Using cached h5py-3.12.1-cp311-cp311-win_amd64.whl.metadata (2.5 kB)
  Using cached optree-0.13.0-cp311-cp311-win_amd64.whl.metadata (48 kB)
  Using cached ml_dtypes-0.5.0-cp311-cp311-win_amd64.whl.metadata (22 kB)
  Using cached markdown_it_py-3.0.0-py3-none-any.whl.metadata (6.9 kB)
  Using cached mdurl-0.1.2-py3-none-any.whl.metadata (1.6 kB)
Using cached keras-3.6.0-py3-none-any.whl (1.2 MB)
Using cached absl_py-2.1.0-py3-none-any.whl (133 kB)
Using cached h5py-3.12.1-cp311-cp311-win_amd64.whl (3.0 MB)
Using cached ml_dtypes-0.5.0-cp311-cp311-win_amd64.whl (211 kB)
Using cached namex-0.0.8-py3-none-any.whl (5.8 kB)
Using cached optree-0.13.0-cp311-cp311-win_amd64.whl (283 kB)
Using cached rich-13.9.2-py3-none-any.whl (242 kB)
Using 

In [ ]:
from keras.models import Sequential #here sequential, dense and activation are just classes from the package keras
from keras.layers import Dense, Activation

model = Sequential([
    Dense(32, input_shape=(10, ), activation='relu'),
    Dense(2, activation='softmax'),
])

In [7]:
pip install scipy

     ---------------------------------------- 0.0/60.8 kB ? eta -:--:--
     ------------ ------------------------- 20.5/60.8 kB 330.3 kB/s eta 0:00:01
     ------------------------- ------------ 41.0/60.8 kB 487.6 kB/s eta 0:00:01
     -------------------------------------- 60.8/60.8 kB 537.6 kB/s eta 0:00:00
   ---------------------------------------- 0.0/44.8 MB ? eta -:--:--
   ---------------------------------------- 0.2/44.8 MB 3.3 MB/s eta 0:00:14
    --------------------------------------- 0.7/44.8 MB 7.7 MB/s eta 0:00:06
   - -------------------------------------- 1.7/44.8 MB 13.7 MB/s eta 0:00:04
   - -------------------------------------- 1.9/44.8 MB 11.2 MB/s eta 0:00:04
   - -------------------------------------- 2.2/44.8 MB 10.1 MB/s eta 0:00:05
   -- ------------------------------------- 2.6/44.8 MB 9.3 MB/s eta 0:00:05
   -- ------------------------------------- 2.9/44.8 MB 9.1 MB/s eta 0:00:05
   -- ------------------------------------- 3.1/44.8 MB 8.6 MB/s eta 0:00:05

In [ ]:
import numpy as np
from scipy import ndimage
import matplotlib.pyplot as plt
%matplotlib inline

img = np.expand_dims(ndimage.imread('NN.PNG'), 0)
plt.imshow(img[0])